export const caseList = [
    {
        id: 1,
        name: 'Eliee Li',
        identity: '家庭',
        num: 4,
        date: '2024',
        taxDesc: '一家四口，长居国内，但想保留CA身份，按自雇规划',
        deduction: '',
        refundAmount: 0,
    },
    {
        id: 2,
        name: 'Jayden Cao',
        identity: '家庭',
        num: 3,
        date: '2024',
        taxDesc: '一家三口，夫妻一方自雇收入一方工资收入+，小孩3岁',
        deduction: '房租抵扣+牛奶金+托儿费抵扣+教育激励',
        refundAmount: 0,
    },
    {
        id: 3,
        name: 'Ms Wang',
        identity: '单亲家庭',
        num: 2,
        date: '2024',
        taxDesc: '单亲家庭，一个人工资收入',
        deduction: '合格家属抵扣+儿童福利+单亲补助+托儿费抵扣+教育激励',
        refundAmount: 12300,
    },
    {
        id: 4,
        name: 'Max Zhao',
        identity: '家庭',
        num: 2,
        date: '2022-2024',
        taxDesc: '夫妻俩人，22年新居民两省分居，一房有工资收入，一方研究生在读',
        deduction: '落地税+搬家抵扣+租房抵扣+学费抵扣',
        refundAmount: 8366,
    },
    {
        id: 5,
        name: 'Knight Tan',
        identity: '个人工签',
        num: 1,
        date: '2024',
        taxDesc: '美国公司公派CA办公，标准工资收入和gic收入',
        deduction: '落地税+搬家抵扣+租房抵扣',
        refundAmount: 0,
    },
    {
        id: 6,
        name: 'Box Sun',
        identity: '自雇',
        num: 1,
        date: '2023-2024',
        taxDesc: '打工人闲时开uber吧，报工资收入、奖金收入、自雇收入，自住房地下室有租金收入',
        deduction: '自雇抵扣（油费+汽车折旧+保险+餐费），房屋出租抵扣（贷款利息、房屋保险、广告费用、房屋装修、日常维护、地产税）',
        refundAmount: 0,
    },
    {
        id: 7,
        name: 'Nicole Li',
        identity: '留学生',
        num: 1,
        date: '2019-2024',
        taxDesc: '工作第一年，报工资收入和GIC',
        deduction: '学费抵扣+落地税+房租抵扣+搬家抵扣',
        refundAmount: 12320,
    }
]